In [1]:
import babypandas as bpd
import numpy as np

# generate-200-CIs

Using this notebook to generate 200 bootstrapped CIs for median salary.

In [2]:
population = bpd.read_csv('data/2023_salaries.csv')
population_median = population.get('TotalWages').median()
population_median

80492.0

In [3]:
def one_ci(n_resamples=500):
    sample = population.sample(500)
    medians = np.array([])
    for i in np.arange(n_resamples):
        resample = sample.sample(500, replace=True)
        resample_median = resample.get('TotalWages').median()
        medians = np.append(medians, resample_median)
    return np.array([np.percentile(medians, 2.5), np.percentile(medians, 97.5)])

In [4]:
many_cis = []
for i in range(200):
    many_cis.append(one_ci())
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [5]:
many_cis

[array([77166.    , 91234.0625]),
 array([71080.1 , 85446.85]),
 array([77012.2875, 92514.075 ]),
 array([73279.25  , 88073.0625]),
 array([75616.6375, 92022.5   ]),
 array([61787.1375, 77301.5375]),
 array([77447.9, 92098.5]),
 array([76094.3125, 90812.1125]),
 array([72010., 85282.]),
 array([64410.9125, 83491.    ]),
 array([65017.    , 83141.4375]),
 array([76069., 93619.]),
 array([71365.875 , 89479.0375]),
 array([71969.325, 85066.   ]),
 array([72690.7875, 85790.8   ]),
 array([72404.7   , 90427.2375]),
 array([70647.275, 85400.   ]),
 array([72536.5   , 87623.2125]),
 array([80297.2, 91453. ]),
 array([67939.4625, 82929.    ]),
 array([76699.675, 89354.1  ]),
 array([73014.575, 87071.   ]),
 array([69343., 83039.]),
 array([69875.    , 88478.2625]),
 array([72145.875, 87107.975]),
 array([67946., 86086.]),
 array([75247., 87416.]),
 array([74902.5125, 90926.35  ]),
 array([75865.075, 92142.975]),
 array([74048.3 , 89535.05]),
 array([79175.8375, 91865.6   ]),
 array([80653.    

In [6]:
np.save('data/many_cis.npy', many_cis)